name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre_scripts:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12.16.3
      - name: Install yarn
        run: |
          sudo npm install -g yarn
  build:
    needs: [pre_scripts]
    runs-on: [self-hosted, Linux]
    steps:
      - uses: actions/checkout@v2
      - name: Install expo-cli
        run: |
          sudo npm install -g expo-cli
      - name: Install deps
        run: |
          yarn
      - name: Configure env
        run: |
          cp .env.sample .env
      - name: Test
        run: |
          yarn test

#       - name: configure env
#         run: |
#           cat << EOF > .env
#           STREAM_API_KEY=test
#           STREAM_API_TOKEN=test
#           STREAM_APP_ID=test
#           EOF

